# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: LEAP
email: akwong@exseed.ed.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://LEAP-Kwong.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: asfkwong
github_username:  kwongsiufung

# Build settings
theme: bulma-clean-theme
# remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed

# Defaults
defaults:
  # pages/
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      hero_height: is-small
      title: "Lifecourse Epidemiological And Psychiatry Research Group"
      